#!/bin/bash

echo "🔧 Setting up frontend code coverage..."
echo ""

# Install coverage provider
echo "1. Installing @vitest/coverage-v8..."
npm install --save-dev @vitest/coverage-v8

echo ""
echo "2. Coverage provider installed ✅"
echo ""
echo "3. Update vite.config.ts to add coverage configuration"
echo "   Add this to your test config:"
echo ""
echo "   coverage: {"
echo "     provider: 'v8',"
echo "     reporter: ['text', 'html', 'json-summary'],"
echo "     exclude: ["
echo "       'node_modules/',"
echo "       'src/test/',"
echo "       '**/*.test.{ts,tsx}',"
echo "       '**/*.config.{ts,js}',"
echo "       '**/types.ts',"
echo "     ],"
echo "     all: true,"
echo "     lines: 90,"
echo "     functions: 90,"
echo "     branches: 85,"
echo "     statements: 90,"
echo "   }"
echo ""
echo "4. Run coverage with: npm run test:coverage"
echo ""
echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Update vite.config.ts with coverage config above"
echo "  2. Run: npm run test:coverage"
echo "  3. Open: coverage/index.html"
